plugins {
    id 'com.android.application'
}

android {
    namespace 'com.youtube.ytdl'
    compileSdk 34

    defaultConfig {
        applicationId "com.youtube.ytdl"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.arthenica:mobile-ffmpeg-full:4.4'
    implementation group: 'net.jthink', name: 'jaudiotagger', version: '3.0.1'

    implementation 'com.github.bumptech.glide:glide:4.12.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'

    implementation 'com.github.sealedtx:java-youtube-downloader:3.2.8'

    implementation 'org.jsoup:jsoup:1.17.1'
    implementation 'cz.msebera.android:httpclient:4.5.8'

    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}
